"""empty message

Revision ID: 12314f19dd61
Revises: 16ffad71df6e
Create Date: 2021-07-04 23:20:17.906503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12314f19dd61'
down_revision = '16ffad71df6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'article_style', ['astyle'], ['id'])
    op.drop_column('article', 'article_style')
    op.drop_column('article', 'article_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_type', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('article_style', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
