"""empty message

Revision ID: 2a554ce926aa
Revises: 
Create Date: 2021-07-04 09:07:00.721804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a554ce926aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=11), nullable=False),
    sa.Column('user_email', sa.String(length=20), nullable=True),
    sa.Column('user_icon', sa.String(length=120), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
