"""empty message

Revision ID: a96a08b23d05
Revises: 322dab3fb882
Create Date: 2021-07-04 20:16:02.053106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96a08b23d05'
down_revision = '322dab3fb882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'is_delete')
    # ### end Alembic commands ###
